### ISSUE TITLE
scaling down segment

### ISSUE THREAD

**Issue by diwu1989** [getcarina/feedback#18] opened 2015-11-08 06:49 UTC
I think it used to be possible to scale down the number of segments, how come it's no longer possible?

**Comment by jnoller** [comment] 2015-11-08 15:36
Heya! Actually we haven't supported scaling down yet. I'm assuming you want to do this yourself via the CLI/UI (remove segments) vs having it happen automatically

**Comment by diwu1989** [comment] 2015-11-13 06:04
yeah I want to be able to remove segments

**Comment by ktbartholomew** [comment] 2016-03-23 13:05
Duplicate of https://github.com/getcarina/feedback/issues/6

**Closed by ktbartholomew** 2016-03-23 13:05 UTC
Labels: carina-backlog
